### ISSUE TITLE
Error: Cannot find module 'fortnitenode'

### ISSUE THREAD

**Issue by oceanman421** [kem0o/neobot#4]
```
  throw err;
  ^

Error: Cannot find module 'fortnitenode'
Require stack:
- C:\Users\ \Downloads\neobot-master\neobot-master\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1090:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:75:18)←[39m
    at Object.<anonymous> (C:\Users\ \Downloads\neobot-master\neobot-master\index.js:4:5)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1201:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1050:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:938:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\ \\Downloads\\neobot-master\\neobot-master\\index.js'←[39m
  ]
}
```

Note: I ran "npm install package.json" before running "index.js".

**Comment by Skadro** [comment]
@oceanman421 Teenari(the owner of the module) deleted his Github account, and automatically the module that he had on the account was deleted so you can no longer download the module until someone else publishes it.
